# Generated by Django 4.2.3 on 2023-07-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gripper', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('motor1_angle', models.IntegerField(default=0)),
                ('motor2_angle', models.IntegerField(default=0)),
                ('motor3_angle', models.IntegerField(default=0)),
                ('motor4_angle', models.IntegerField(default=0)),
                ('motor5_angle', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('movement1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence1', to='cobot.movement')),
                ('movement2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence2', to='cobot.movement')),
                ('movement3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence3', to='cobot.movement')),
                ('movement4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence4', to='cobot.movement')),
                ('movement6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence5', to='cobot.movement')),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='point1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_point1', to='cobot.point'),
        ),
        migrations.AddField(
            model_name='movement',
            name='point2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_point2', to='cobot.point'),
        ),
        migrations.AddField(
            model_name='movement',
            name='point3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_point3', to='cobot.point'),
        ),
        migrations.AddField(
            model_name='movement',
            name='point4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_point4', to='cobot.point'),
        ),
        migrations.AddField(
            model_name='movement',
            name='point5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_point5', to='cobot.point'),
        ),
    ]
