# Generated by Django 4.2.3 on 2023-07-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobot', '0004_alter_movement_point1_alter_movement_point2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='movement6',
            new_name='movement5',
        ),
    ]
