# Generated by Django 4.2.3 on 2023-07-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobot', '0005_rename_movement6_sequence_movement5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
