# Generated by Django 4.2.2 on 2023-08-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobot', '0007_alter_sequence_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='movement10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence10', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence11', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence12', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement13',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence13', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement14',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence14', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement15',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence15', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement16',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence16', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement17',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence17', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement18',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence18', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement19',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence19', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement20',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence20', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement21',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence21', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence22', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement23',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence23', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement24',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence24', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement25',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence25', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence6', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence7', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence8', to='cobot.movement'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='movement9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence9', to='cobot.movement'),
        ),
    ]
