# Generated by Django 4.2.2 on 2023-08-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobot', '0008_sequence_movement10_sequence_movement11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='motor1_angle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='point',
            name='motor2_angle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='point',
            name='motor3_angle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='point',
            name='motor4_angle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='point',
            name='motor5_angle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
