# Generated by Django 4.2.2 on 2023-08-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobot', '0009_alter_point_motor1_angle_alter_point_motor2_angle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='motor1_angle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='point',
            name='motor2_angle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='point',
            name='motor3_angle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='point',
            name='motor4_angle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='point',
            name='motor5_angle',
            field=models.FloatField(default=0.0),
        ),
    ]
